minimumReleaseAge: 10080 # Only install package versions that have been published for at least 7 days.
minimumReleaseAgeStrict: true
blockExoticSubdeps: false # Allow exotic subdependencies (required for ZKsync dependency `@matterlabs/zksync-telemetry-js` (resolved via git repository)).
allowBuilds:
  cpu-features: true
  keccak: true
  protobufjs: true
  secp256k1: true
  ssh2: true
